#
# Copyright (c) 2012 by Pawel Tomulik
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE


Import('env')

from SConsGnuBuild.GnuDirVars import StandardDirGVarDecls

only = ('prefix','exec_prefix','bindir')

dir_gdecls = StandardDirGVarDecls(name_filter = lambda x : x in only)

cli_vars = Variables()
dir_gvars = dir_gdecls.Commit(env, cli_vars, True)
dir_gvars.UpdateEnvironment(env, cli_vars, True, ARGUMENTS)

Help(dir_gvars.GenerateVariablesHelpText(cli_vars, env))

# NOTE: only our `GVars` are available through this environment proxy,
#       so env['CXX'] for example will cause a KeyError exception
proxy = dir_gvars.get_env_proxy(env)

if not GetOption('help'):
    print ""
    print "There are three `GVar` variables representing GNU directory"
    print "variables. They are currently defined as:"
    print "=========================================================="
    print "     prefix=%s" % repr(proxy['prefix'])
    print "     exec_prefix=%s" % repr(proxy['exec_prefix'])
    print "     bindir=%s" % repr(proxy['bindir'])
    print "=========================================================="
    print ""
    print "After substitution (interpolation) they have values:"
    print "=========================================================="
    print "     prefix=%s" % repr(proxy.subst('${prefix}'))
    print "     exec_prefix=%s" % repr(proxy.subst('${exec_prefix}'))
    print "     bindir=%s" % repr(proxy.subst('${bindir}'))
    print "=========================================================="
