language: python
python:
  - "2.6"
  - "2.7"
    #  - "3.2"
    #  - "3.3"
install:
  - "./bin/download-deps.sh"
  - "sudo apt-get install scons"
  - "sudo apt-get install python-epydoc python-docutils python-pygments"
  - "sudo apt-get install docbook5-xml xsltproc imagemagick"
script:
  - "scons unit-test"
  - "SCONS_EXTERNAL_TEST=1 python runtest.py -a"
  - "scons user-doc"
  - "scons api-doc"
