language: python
python:
  - "2.6"
  - "2.7"
    #  - "3.2"
    #  - "3.3"
install:
  - "./bin/download-deps.sh"
  - "sudo apt-get install scons"
script:
  - "scons unit-test"
  - "SCONS_EXTERNAL_TEST=1 python runtest.py -a"
